version: "3.9"

services:
  artes-service:
    build: ./service
    restart: unless-stopped
    expose:
      - "4010"
    volumes:
      - ./src/temp:/usr/src/app/src/temp
    depends_on:
      - db
      - minio

  artes-ui:
    build: ./ui
    restart: unless-stopped
    expose:
      - "80"
    depends_on:
      - artes-service

  nginx:
    build: ./nginx
    container_name: artes-nginx
    restart: unless-stopped
    ports:
      - "80:80"
    depends_on:
      - artes-ui
      - artes-service

  db:
    build: ./db
    restart: unless-stopped
    environment:
      POSTGRES_DB: artes_reports
      POSTGRES_USER: artes
      POSTGRES_PASSWORD: artes
    volumes:
      - pg_data:/var/lib/postgresql/data

  minio:
    image: minio/minio
    restart: unless-stopped
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: artes
      MINIO_ROOT_PASSWORD: artes123
    ports:
      - "9001:9001"   # console only
    volumes:
      - minio_data:/data

  minio-init:
    image: minio/mc
    depends_on:
      - minio
    entrypoint: >
      /bin/sh -c "
      mc alias set local http://minio:9000 artes artes123 &&
      mc mb -p local/artes-reports
      "

volumes:
  pg_data:
  minio_data:
